version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    env_file:       # lee variables desde .env (recomendado)
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "${MYSQL_HOST_PORT:-3306}:3306"   # opcional: publica MySQL fuera del contenedor
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d:ro   # scripts SQL/ .sh para inicializar (opcional)
    networks:
      - db_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      # PMA_USER / PMA_PASSWORD no es necesario salvo que quieras conectar por defecto
    ports:
      - "${PHPMYADMIN_HOST_PORT:-8080}:80"
    networks:
      - db_network

volumes:
  db_data:

networks:
  db_network:
    driver: bridge
